services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/GiangDN1001/WebBanHang
    branch: main
    dockerfilePath: ./Dockerfile

    buildCommand: |
      composer install --no-dev --prefer-dist --optimize-autoloader
      php artisan config:clear
      php artisan key:generate
      php artisan session:table
      php artisan migrate --force

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
