services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/your-username/your-repo
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      php artisan key:generate
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
